# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1e41bc25b27235824c34d19963ecba763b92178717a480d6e3223d2f94969e5b0c18c066fd874cb8bbb9de8a5fc0f96fb371305a11098876d102579353118e8

test:
  secret_key_base: 7f8f0f3337c177f7fa2cd15062890c242d7cb3cb969e2b50ee7c7e7ad62201f98fcd4c75d661fb26906a3dc66fcdb20d8a39d23c11f787c2bfaccf95d07ef984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
